# 기본 설정 파일
defaults:
  - _self_
  - models: sam2
  - trackers: bytetrack
  - data: default
  - visualization: default
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# 일반 설정
general:
  seed: 42
  device: cuda  # cuda 또는 cpu
  debug: false
  save_results: true
  output_dir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d_%H-%M-%S}

# 실행 모드 설정
run:
  mode: video  # video 또는 webcam
  video_path: ${data.video_path}
  save_video: true
  display: true
  num_objects: 5  # 추적할 객체 수
  
hydra:
  run:
    dir: ${general.output_dir}
  sweep:
    dir: ${general.output_dir}
    subdir: ${hydra.job.num}
  job:
    chdir: true
