defaults:
  - experiment/default
  - dataset: default
  - model: default
  - _self_

# 하이드라 설정
hydra:
  run:
    dir: ${logging.save_dir}/${experiment.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${logging.save_dir}/${experiment.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        exclude_keys:
          - experiment.name
          - logging.save_dir
          - hydra.run.dir
          - hydra.sweep.dir

# 실행 설정
run:
  mode: train  # train, test, visualize
  device: auto  # auto, cpu, cuda
