defaults:
  - model: openai
  - _self_

data:
  file_path: "data/all you need is attention.pdf"
  chunk_size: 500
  chunk_overlap: 50
  splitter_type: "recursive"

general:
  log:
    path: "logs/rag_pipeline.log"

retriever:
  top_k: 5
  search_type: "similarity"

vectordb:
  save_path: "data/vector_store"  # 벡터 DB 저장 경로
  debug: true  # 디버그 출력 여부

memory:
  max_history: 5  # 저장할 최대 대화 이력 수
