# CIFAR-10 데이터셋 설정
dataset:
  name: 'cifar10'
  paths:
    root: './data'  # 데이터 저장 경로

  transform:
    train:
      - name: RandomCrop
        size: 32
        padding: 4
      - name: RandomHorizontalFlip
      - name: ToTensor
      - name: Normalize
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]

    test:
      - name: ToTensor
      - name: Normalize
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]

  dataloader:
    train:
      batch_size: 32
      shuffle: true
      num_workers: 4
      pin_memory: true
      drop_last: true

    test:
      batch_size: 32
      shuffle: false
      num_workers: 4
      pin_memory: true
      drop_last: false

  properties:
    image_size: [32, 32]  # 이미지 크기 (높이, 너비)
    channels: 3           # 채널 수 (RGB)
    num_classes: 10       # 클래스 수
    train_size: 50000     # 학습 데이터 크기
    test_size: 10000      # 테스트 데이터 크기 